# Generated by Django 3.2.5 on 2021-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.BigIntegerField(verbose_name='Высота блока')),
                ('block_hash', models.CharField(max_length=64, verbose_name='Хеш блока')),
                ('timestamp', models.BigIntegerField(verbose_name='Время блока')),
                ('miner_address', models.CharField(help_text='Его публичный хеш', max_length=34, verbose_name='Адрес майнера')),
                ('transaction_quantity', models.IntegerField(verbose_name='Количество транзакций')),
            ],
            options={
                'verbose_name': 'Блок блокчейна',
                'verbose_name_plural': 'Блоки блокчейна',
                'db_table': 'blockchain_block',
                'ordering': ['-timestamp'],
            },
        ),
    ]
